server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_test_shiro?serverTimezone=GMT%2B8
    username: root
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver
