server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello?serverTimezone=GMT%2B8
    username: root
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver

