spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ahhTou.bean
  configuration:
    cache-enabled: true
    local-cache-scope: statement
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null


ahhtou:
  utils:
    img:
      searcher:
        proxy-url: http://39.99.154.145/img/hello/
        cycle-time: 5
        img-regs:
          - .*.jpg
          - .*.png
    email-sender:
      mySenderPassword: EEQDRTMEKQDONCRC
      mySenderEmail: ahhTou@163.com


