mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ahhTou.bean
  configuration:
    cache-enabled: true
    local-cache-scope: statement
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null


ahhtou:
  utils:
    img:
      searcher:
        cycle-time: 5
        img-regs:
          - .*.webp
    email-sender:
      mySenderPassword: LZHNBGGZMFTPIZML
      mySenderEmail: ahhTou@163.com
    var:
      size:

        width: 150
        height: 250



spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    druid:
      initial-size: 5 # 初始化大小
      min-idle: 5 #最小链接数
      max-active: 20 # 最大链接数
      max-wait: 60000 # 连接等待操死时间
      timeBetweenEvictionRunsMillis: 60000  #配置隔多久进行一次检测(检测可以关闭的空闲连接)，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  #配置连接在池中的最小生存时间
      validationQuery: SELECT 1 FROM DUAL   #校验sql、oracle配置，如果不配置validationQuery，则下面三项无效
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true # 打开PSCache，并且指定
      maxPoolPreparedStatementPerConnectionSize: 20 # 每个连接上PSCache的大小
      filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall' 用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true #合并多个DruidDataSource的监控数据
      stat-view-servlet.enabled: true   #查看








